# Site settings
title: Travel Blog
email: funtravel@gmail.com
description: a fun blog about travelling.
baseurl: "/travel-blog"
twitter_username: ashowofhands
avatar: "https://pbs.twimg.com/profile_images/477656140176564224/OQ8ggAOg.jpeg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Oliver Browne" # Set default author name
      categories: "places"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
